# Site settings
title: Shivam Mohan
email: shivamohan07@gmail.com
name: Shivam Mohan (shivamohan07@gmail.com)

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/Shivamohan07
 - title: LinkedIn
   url: https://www.linkedin.com/in/shivam-mohan-99aa1082/
   
#Any buzzword skills you want to include
skills:
 - Java (Proficient)
 - Apache Spark (Proficient)
 - Apache Kafka (Proficient)
 - Apache Hadoop (Proficient)
 - Apache Hive (Proficient)
 - Apache Hbase (Intermediate)
 - Docker (Intermediate)
 - Jenkins (Proficient)
 - Chef (Beginner)
 - GO Lang (Beginner)
 - GIT (Proficient)
 - Shell Scripting (Proficient)
 - CI/CD

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Sr. Software Engineer
   start: 2018
   end: Ongoing
   employer: Visa Inc
   description:
 - title: Software Engineer
   start: 2017
   end: 2018
   employer: Visa Inc
   description: 
 
   
#Education is required
education:
 - level: B.Tech
   date: 2017
   subject: Computer Science and Engineering (8.78 CGPA)
   school: Motilal Nehru National Institute of Technology, Allahabad

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
    

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
   

#List of interesting Github repo/projects to include - optional
github:
 - Shivamohan07/shivamohan07.github.io



#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/5362755/shivam-mohan
   flairimageurl: https://stackoverflow.com/users/flair/5362755.png?theme=clean

intro: |
  I am Computer Science and Engineering graduate from Motilal Nehru National Institute of Technology, working with the Visa's Data Platform Team, in the domain of Big Data for the last 2 years. </br>
  Major focus of my work has been on building ETL pipelines that can handle an enormous loads of data and provision information as fast as possible. </br>
  I have worked on both batch processing as well as real time data processing and hence is well versed with the designing and programming paradigms of both the vertical
  of Big Data Processing. </br>
  I have also made major contribution for the development of a streamlined code integration and code deployment process for my organization.</br> 
  I am a technology enthusiast always looking to learn new technologies and use them to enhance my skills. In my spare time, I like to read technology journals
  and love to watch conference talks.</br>



professionalexp: |
 <p>
 <b>Project:</b> Rearchitect Enterprise Data Warehouse (EDW) </br>
 <b>Role:</b> Developer</br>
 <b>Scope:</b> The aim of this project was to migrate the existing data warehouse from propriety-based storage system to Hadoop, an open source distributed file system.</br>
 <b>Technology Stack:</b> Hadoop, Spark, Java.</br>
 </br>
 <b>Project:</b> CI/CD (Continuous Integration and Continuous Deployment) Pipeline</br>
 <b>Role:</b> Design, Developer</br>
 <b>Scope:</b> The aim of the project was to create an automated code deployment pipeline. I worked as a developer on the project, and designed an integrated deployment pipeline.</br>
 <b>Technology Stack:</b> Jenkins, Chef, Groovy, RPM, Maven-Archetype</br>
 </br>
 <b>Project:</b> Apple Pay</br>
 <b>Role:</b> Developer</br>
 <b>Scope:</b> This project is in collaboration with Apple to enable real time device notifications for all Apple Pay transactions.</br>
 <b>Technology Stack:</b> Kafka, HBase, Java.</br>
 </p>
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   
   <b>Extra-curricular:</b> </br>
   <ul>
    <li>Actively participated in debate & group discussions at school.</li>
    <li>Won Table Tennis Championship for 2 years successively at school in singles and doubles category. </li>
    <li> Member of SMILE Foundation, an NGO working for welfare of underprivileged children. </li>
   </ul>  
   <b> Honors: </b></br>
   <ul>
    <li>Received Star of the Quarter award from Visa, for outstanding performance in Quarter III of FY17-18.</li>
   </ul>    
   
  
theme: jekyll-theme-architect
